#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    echo "grl: (G)rep (L)ocal (L)ogfiles"
    echo "Usage: gll <keyword>"
    exit 1
fi

KEYWORD=$1
shift

LOGS_DIR="/srv/timbos-hn-reader/logs/" # Ensure this path is correct

for file in "${LOGS_DIR}thnr-combined-"*.log; do
    grep --color --perl-regexp --text "${KEYWORD}" "$@" "${file}"
done
