#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    echo "gol: (G)rep (O)ld (L)ogfiles"
    echo "Usage: gol <keyword> [additional grep options]"
    exit 1
fi

KEYWORD=$1
shift

OLD_LOGS_DIR="/mnt/synology/logs/thnr2.home.arpa/"

for file in "${OLD_LOGS_DIR}thnr-thnr-"*.log; do
    grep --color --perl-regexp --text "${KEYWORD}" "$@" "${file}"
done
