#!/usr/bin/env bash

# debugging switches
# set -o errexit   # abort on nonzero exitstatus; same as set -e
# set -o nounset   # abort on unbound variable; same as set -u
set -o pipefail  # don't hide errors within pipes
# set -o xtrace    # show commands being executed; same as set -x
# set -o verbose   # verbose mode; same as set -v

source /srv/timbos-hn-reader/functions.sh
source /srv/timbos-hn-reader/thnr-common-functions.sh

if [[ -n ${1+x} && -n ${1} ]]; then
    day="${1}"
else
    day=$(printf "%03d" $((10#$(date +%j))))
fi

echo "/srv/timbos-hn-reader/logs/thnr-combined-2024-${day}.log"
