


---

CANONICAL_URL:
  LM:
    owl: https://www.thnr.net/
    thnr: https://dev.thnr.net/
  DM:
    owl: https://www.thnr.net/dm/
    thnr: https://dev.thnr.net/dm/
  
HEADER_HYPERLINK:
  LM:
    owl: file:///D:/var/www/thnr.net/hn_stories/top_stories_page_1.html
    thnr: https://dev.thnr.net/
  DM:
    owl: file:///D:/var/www/thnr.net/hn_stories/top_stories_page_1_dm.html
    thnr: https://dev.thnr.net/dm/

ABOUT_HTML_URL:
  LM:
    owl: file:///D:/var/www/thnr.net/public_html/about.html
    thnr: https://dev.thnr.net/about/
  DM:
    owl: file:///D:/var/www/thnr.net/public_html/about-dm.html
    thnr: https://dev.thnr.net/dm/


SHORT_URL_DISPLAY:
  owl: thnr.net
  thnr: dev.thnr.net

DELEGATES:
  PDF2PNG:
    owl: L:/utils/gs/bin/gswin64c.exe
    thnr: /usr/local/bin/gs

TEMP_DIR:
  owl: D:/temp/thnr/
  thnr: /tmp/

THNR_BASE_DIR:
  owl: D:/timbos-hn-reader/
  thnr: /srv/timbos-hn-reader/

STATIC_URL:
  owl: D:/var/www/thnr.net/static/
  thnr: /static/

STORIES_URL:
  owl: D:/var/www/thnr.net/hn_stories/
  thnr: https://dev.thnr.net/

THUMBS_URL:
  owl: https://thnrcdn.com/thumbs/
  thnr: https://thnrcdn.com/thumbs/

PAGES:
  NUM_STORIES_PER_PAGE: 20

OG_IMAGE:
  MIN_DIM_PX: 250

THUMBS:
  COMP_QUAL:
    SMALL: 80
    MEDIUM: 65
    LARGE: 50
    EXTRALARGE: 50
  WIDTH_PX:
    SMALL: 350
    MEDIUM: 700
    LARGE: 1050
    EXTRALARGE: 1400
  CLIENT_MIN_WIDTH_PX:
    FOR_SMALL: 375
    FOR_MEDIUM: 575    
    FOR_LARGE: 768
    FOR_EXTRALARGE: 768
  BG_COLOR_FOR_TRANSPARENT_THUMBS: "#FFFFFF"

WAND:
  FUZZ_FACTOR_PCT: 0
  BORDER_EXPANSION_PCT: 5
  RATIO_TOLERANCE_PCT: 22
  MIN_DIM_FOR_SQUARE_ASPECT_PX: 720

SLUGS:
  MAX_SUBSTRING_LENGTH: 32
  CHAR_LENGTH_FOR_LINEWRAPPING_DOMAINS: 20

SCRAPING:
  UA_STR: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
  PERMITTED_STORY_TYPES: ["top", "new", "best", "active", "classic"]
  STORY_ROSTERS: ["top", "new", "best", "active", "classic"]
  REQUESTS_GET_TIMEOUT_S: 16
  FIREBASEIO_RETRY_DELAY: 8
  NUM_RETRIES_FOR_HN_FEEDS: 3
  # ensure that chromedriver and chrome browser are same version
  PATH_TO_CHROMEDRIVER: "/srv/timbos-hn-reader/bin/chromedriver/116.0.5845.96/chromedriver"
  PATH_TO_CHROME_BROWSER: "/usr/bin/google-chrome-stable"

SYMBOLS:
  DATA_SEPARATOR: "·"
  NONBREAKING_HYPHEN: "&#8209;"
  DOUBLE_OBLIQUE_HYPHEN: "&#11799;"

MINUTES_BEFORE_REFRESHING_STORY_METADATA: 60
